version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: HRBackend/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000
    networks:
      - fullstack

  frontend:
    build:
      context: .
      dockerfile: HRFrontend/Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - fullstack

networks:
  fullstack:
    driver: bridge
